#!/usr/bin/env bash

draw() {
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in 
  image/*)
    draw "$file"
    ;;
  video/*)
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(vidthumb "$file")"
    ;;
  application/pdf)
    filename=$(basename $(echo "$file" | tr ' ' '_'))
    if [[ ! -f "/tmp/$filename.png" ]]; then
            pdftoppm -f 1 -l 1 "$file" >> "/tmp/$filename.png"
    fi
    # draw "/tmp/$filename.png"
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "/tmp/$filename.png" < /dev/null > /dev/tty
      exit 1
    ;;

  *)
      bat --color=always --plain "$file" 
    ;;

esac

pistol "$file"
