#!/usr/bin/env bash

draw() {
  # CACHE="$HOME/.cache/lf/thumb"
  # mkdir -p "$CACHE"
  #
  # HASH=$(printf '%s' "$1" | md5sum | cut -d' ' -f1)
  # THUMB="$CACHE/$HASH.jpg"
  #
  # if [ ! -f "$THUMB" ]; then
  #   magick "$1"[0] -thumbnail 800x800 "$THUMB" >/dev/null 2>&1
  # fi

  kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  #
  # chafa --view-size="${w}x${h}" --view-position="${x},${y}" --scale "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in
image/*)
  draw "$file"
  # draw "/tmp/$(basename "$file")"
  ;;
video/*)
  # vidthumb is from here:
  # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
  draw "$(vidthumb "$file")"
  ;;
application/pdf)
  filename=$(basename $(echo "$file" | tr ' ' '_'))
  if [[ ! -f "/tmp/$filename.png" ]]; then
    pdftoppm -f 1 -l 1 "$file" >>"/tmp/$filename.png"
  fi
  # draw "/tmp/$filename.png"
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "/tmp/$filename.png" </dev/null >/dev/tty
  exit 1
  ;;

*)
  bat --theme="base16" --color=always --plain "$file"
  ;;

esac

pistol "$file"
