#!/usr/bin/env bash
#
# Current Theme
dir="$HOME/.config/wofi/powermenu/type-1"
theme='style-3'

# CMDs
#
artist="$(playerctl metadata artist)"
title="$(playerctl metadata title)"
status="$(playerctl -p spotify status)"


# Options
play='󰐊'
pause='󰏤'
prev='󰒮'
stop='󰓛'
next='󰒭'

# wofi CMD
wofi_cmd() {
	wofi -dmenu \
		-p "$artist - $title" \
		-theme ${dir}/${theme}.rasi
}

echo $status
# Pass variables to wofi dmenu
run_wofi() {
if [[ $status == 'Playing' ]]; then
	echo -e "$prev\n$pause\n$next" | wofi_cmd
elif [[ $status == 'Paused' ]]; then
  echo -e "$prev\n$play\n$next" | wofi_cmd
fi

	# echo -e "$prev\n$play\n$stop\n$next" | wofi_cmd
}

# Execute Command
run_cmd() {
  if [[ $1 == '--stop' ]]; then
    playerctl -p spotify stop
  elif [[ $1 == '--play' ]]; then
    playerctl -p spotify play
  elif [[ $1 == '--pause' ]]; then
    playerctl -p spotify pause
  elif [[ $1 == '--prev' ]]; then
    playerctl -p spotify previous
  elif [[ $1 == '--next' ]]; then
    playerctl -p spotify next
  fi
}

# Actions
chosen="$(run_wofi)"
case ${chosen} in
    $prev)
		run_cmd --prev
        ;;
    $pause)
    run_cmd --pause
    echo PAUSE
        ;;
    $play)
    echo PLAY
		run_cmd --play
        ;;
    $stop)
    run_cmd --stop
        ;;
    $next)
		run_cmd --next
        ;;
esac
