#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

dir="$HOME/.config/wofi/launchers/type-1"
theme='style-2'

wallpapers=$HOME/Pictures/Wallpapers/
image="$(ls -t $wallpapers | wofi -dmenu -i -p "  Wallpapers: " -theme ${dir}/${theme}.rasi)"
wallpaper=$wallpapers/$image

if [[ -d $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a directory"
    wallpaper_temp="$image"
    sleep2
    # wallpaper_location="$(ls $wallpapers/$image | wofi -n --show dmenu -k "/dev/null")"
elif [[ -f $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a file"
else
    echo "$wallpapers/$image is not valid"
    exit 1
fi

swww img $wallpaper --transition-type random --transition-fps 60 --transition-duration 0.5 --transition-bezier 0.65,0,0.35,1 --transition-step 1

sleep 1.25


